# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='班级',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='老师姓名',
        ),
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='班级'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='老师姓名'),
            preserve_default=False,
        ),
    ]
