# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_auto_20180419_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='姓名',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='姓名'),
            preserve_default=False,
        ),
    ]
